name: Reso_venue
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.4+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  provider: ^4.0.0
  shared_preferences: any
  json_serializable: ^3.3.0
  build_runner: ^1.7.2
  flutter_launcher_icons: ^0.7.4
  url_launcher: any
  curved_navigation_bar: ^0.3.2
  google_maps_flutter: 0.5.24+1
  qr_code_scanner: ^0.0.13
  qr_flutter: ^3.1.0
  flutter_spinkit: ^4.1.2
  flutter_circular_chart: 0.1.0
  uuid: 2.0.4
  flutter_datetime_picker: 1.3.8
  geolocator: ^5.3.1
  font_awesome_flutter: '>= 4.7.0'
  equatable: ^1.1.1
  dartz: ^0.9.1
  mockito: ^4.1.1
  data_connection_checker: ^0.3.4
  http: ^0.12.1
  bloc: ^4.0.0
  validators: ^2.0.0
  get_it: ^4.0.2
  flutter_bloc: ^4.0.0
  cached_network_image: ^2.2.0+1
  auto_route: ^0.5.0
  flare_flutter: ^2.0.3
  numberpicker: ^0.1.6
  route_observer_mixin: 1.2.0
  share: ^0.6.4+3


dependency_overrides:
  build:
    git:
      url: https://github.com/dart-lang/build.git
      path: build
  build_resolvers:
    git:
      url: https://github.com/dart-lang/build.git
      path: build_resolvers
      
dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.5.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_icons:
  image_path_android: "assets/launcher/Android/App Icon/GooglePlay.png"
  image_path_ios: "assets/launcher/iOS/iTunesArtwork@2x.png"
  android: true 
  ios: true 
  adaptive_icon_background: "assets/launcher/Android/Adaptive App Icon/App Icon Back.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/launcher/Android/Adaptive App Icon/App Icon Front.png"


flutter:

  uses-material-design: true

  assets:
     - assets/
     - lib/lang/